from __future__ import annotations


DEFAULT_ALERT_THRESHOLD = 0.5
DEFAULT_WINDOW_SECONDS = 30
DEFAULT_TIME_BIN_SECONDS = 2
DEFAULT_TOP_EVIDENCE_ITEMS = 3
DEFAULT_BENIGN_CORPUS_DIR = "data/benign_corpus_v3"
DEFAULT_BENIGN_HOLDOUT_RUN_ID = "run_d"
DEFAULT_BBK_TRAIN_WINDOW_SECONDS = 30
DEFAULT_BBK_MIN_TRAIN_WINDOWS = 100
DEFAULT_BBK_MIN_CALIBRATION_WINDOWS = 20
DEFAULT_BBK_MIN_SOURCE_RUNS = 3
DEFAULT_BBK_PROFILE_IMBALANCE_RATIO = 0.4
